### ISSUE TITLE
add the integrated Updater

### ISSUE THREAD

**Issue by godbout** [godbout/WooshyWindowToTheForeground#1]
https://github.com/godbout/AlfredWorkflowUpdater

**Comment by godbout** [comment]
will need to be called in the background, not like Alfred Kat. was ok in the foreground with Alfred Kat because it has to crawl through KAT anyways. doesn't add much time. but for this Workflow the time is gonna be sensitive.

**Comment by clouedoc** [comment]
I don't understand anything, but it's fantastic

**Comment by godbout** [comment]
reading what i wrote again and i don't understand anything either.

**Comment by godbout** [comment]
done in 1.3.0! new Updater 2.0.0. check for updates in the background aww
