### ISSUE TITLE
Possible to add filter to exclude certain apps?

### ISSUE THREAD

**Issue by spencertiedge** [godbout/WooshyWindowToTheForeground#15]
Hi there —

Love this workflow and Wooshy; with the most recent update, I'm seeing some apps that I wasn't seeing in 2.2.0 e.g., Lunar, when there aren't any actual windows to action on.

<img width="718" alt="image" src="https://user-images.githubusercontent.com/75261143/218337830-17de6aad-f36a-4678-802c-22527e953992.png">

Is there a way to add a filter so that certain apps or window names don't show?

**Comment by godbout** [comment]
> with the most recent update, I'm seeing some apps that I wasn't seeing in 2.2.0 e.g., Lunar, when there aren't any actual windows to action on.

alright, will check. thanks.

> Is there a way to add a filter so that certain apps or window names don't show?

currently no. not planning to add either. the idea is that it works out of the box, and if there's issues then people open an GH Issue, like you did. then it's my job to figure out how to make the whole thing better. but i don't want users to be fiddling with options.

**Comment by godbout** [comment]
just installed Lunar. i can't get to see your Alfred results. which means i need some of your Lunar options to know how to catch those "windows".

**Comment by godbout** [comment]
also, regarding your question `Possible to add filter to exclude certain apps?`

better not filter by app. within the same app you will want to see some windows, while you will want to ignore others. which is why i'm handling the filtering the way i do currently (may change in the future).

**Comment by spencertiedge** [comment]
Hey @godbout; apologies for the delay in my response here. I haven't quite figured out what within Lunar is causing the 'gamma' to show up (and when it does, it shows up once per monitor). However, I have found that a simple quit and restart of the Lunar app is enough to have it go away, at least temporarily.

This fixes my issue for now; thanks for your help here and producing this great workflow.

**Comment by learn2reid** [comment]
Can we revisit this for istat menus for example, would love to filter specific apps out

**Comment by godbout** [comment]
> Can we revisit this for istat menus for example, would love to filter specific apps out

sounds fair. can you open a new issue, explain the reason why, a maybe add some fun life story in it? lol thx xoxo

**Comment by godbout** [comment]
> sounds fair. can you open a new issue, explain the reason why, a maybe add some fun life story in it? lol thx xoxo

created it myself: https://github.com/godbout/WooshyWindowToTheForeground/issues/18
please add your thoughts.

**Comment by godbout** [comment]
coming soon: https://github.com/godbout/WooshyWindowToTheForeground/issues/18#issuecomment-2649146643

**Comment by godbout** [comment]
added in 3.4.0: https://github.com/godbout/WooshyWindowToTheForeground/releases/tag/3.4.0
