### ISSUE TITLE
HazeOver

### ISSUE THREAD

**Issue by theovo** [godbout/WooshyWindowToTheForeground#17]
HazeOver, when running in the background, shows up on the list. How can we hide the application when it's not running any windows?

<img width="678" alt="Screenshot 2024 08 08 @ 20 59 01" src="https://github.com/user-attachments/assets/b76cd619-a439-4aa4-b557-a4c83bf85f72">

**Comment by godbout** [comment]
> HazeOver, when running in the background, shows up on the list. How can we hide the application when it's not running any windows?

it's actually running a window, but with opacity set to 0. so it's there but you can't see it lol

special cases like those need to be handled manually. see https://github.com/godbout/WooshyWindowToTheForeground/blob/e4c2764b52aae22eabe3c27be33b11ecac4cc01f/Sources/WooshyWindowToTheForeground/Menus/Entrance.swift#L103
i have to add an exception for HazeOver and make a new release. thanks for the report. will do.

**Comment by theovo** [comment]
Thx for letting me know. I'll wait for the next release.

**Comment by godbout** [comment]
planning to have a look at it tomorrow. research and implementing should be straightforward but i'm more afraid about codesigning and notarizing the binary lol

**Comment by theovo** [comment]
No rush. I like how fast it runs.

**Comment by godbout** [comment]
ok so there's two windows available in HazeOver: 1) the window that adds the layer behind the frontmost window 2) the Settings window. i can't ban HazeOver completely else you'll not be able to grab the Settings window. now HazeOver doesn't name its windows which means the only way to differentiate between the layer one and the Settings is the opacity, _most of the time_. basically it will work nicely only if you don't set the HazeOver layer window to 100, the max. coz in that case i can't differentiate between the layer and the Settings window. if you were using 100, you'll just need to put it at 99. you can't see the difference, but WWTTF will. will be available in 3.2.0 soon.

**Comment by godbout** [comment]
done in https://github.com/godbout/WooshyWindowToTheForeground/releases/tag/3.2.0
you can download directly or wait a bit and the update will be available in the Alfred Gallery ✌️

**Comment by theovo** [comment]
Got it.

The next time I want pitch blackness, I can set HazeOver to 99, instead of 100.

I'm glad we can select the settings window from the list whenever it's visible.

Thanks for providing a solution to my dilemma. Your swiftness is appreciated.

**Comment by godbout** [comment]
this has changed in the latest version of WWTTF: https://github.com/godbout/WooshyWindowToTheForeground/releases/tag/3.4.0

now WWTTF filters out macOS and Alfred Windows out of the box, but doesn't care about third party apps. third party apps Windows can now be banned/unbanned directly from the Workflow (command key to ban, `-ww` to see the list of banned Windows).
