### ISSUE TITLE
Not support app list

### ISSUE THREAD

**Issue by NavinChen** [godbout/WooshyWindowToTheForeground#8]
1. QQ
2. Wechat
3. Dingtalk
4. em client
5. typora
6. switchhosts

**Comment by godbout** [comment]
cool. that's a nice list. will have a look. 谢谢.

**Comment by NavinChen** [comment]
> cool. that's a nice list. will have a look. 谢谢.

Thank you to the author for your time and effort, thanks

**Comment by godbout** [comment]
> Thank you to the author for your time and effort, thanks

i will tell him. but first i will make him work relentlessly.

**Comment by godbout** [comment]
hi again.

i've tried four of them and they all work. see below:

https://user-images.githubusercontent.com/121373/180373647-e6048616-741c-4319-9277-e7d33d0b598a.mp4

so:

1. have you installed the Workflow?
2. have you tried the Workflow?
3. Marco is that you? are you joking to me?

**Comment by NavinChen** [comment]
> hi again.
> 
> i've tried four of them and they all work. see below:
> 
>  ScreenFlow.mp4 
> so:
> 
> 1. have you installed the Workflow?
> 2. have you tried the Workflow?
> 3. Marco is that you? are you joking to me?

1. installed the workflow
2. em client doesn't know why it works again, it didn't work just now
3. sorry i don't know who macro is……

**Comment by NavinChen** [comment]
> hi again.
> 
> i've tried four of them and they all work. see below:
> 
>  ScreenFlow.mp4 
> so:
> 
> 1. have you installed the Workflow?
> 2. have you tried the Workflow?
> 3. Marco is that you? are you joking to me?

1. installed the workflow
2. em client doesn't know why it works again, it didn't work just now
3. sorry i don't know who macro is……

**Comment by godbout** [comment]
没问题.

please note this part from the README:
* all visible windows are listed **except the already currently focused one**

if your window is the one currently focused, it will not show up in the list. because it makes no sense to have it there and it pollutes the results.

**Comment by NavinChen** [comment]
I see, it's because of that, thanks

**Comment by NavinChen** [comment]
thank you very much

**Comment by godbout** [comment]
bù kè qi. 

enjoy and have fun.

**Comment by fabOnReact** [comment]
does not work for me

**Comment by godbout** [comment]
@fabriziobertoglio1987 what does that mean? those apps? all apps? what "does not work" exactly?

please open a new issue and describe properly your issue. thanks.
